# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_more_info',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_header', models.ImageField(upload_to='static/users/headers', verbose_name='用户头像')),
                ('u_autograph', models.CharField(max_length=256, verbose_name='个性签名')),
                ('u_nick_name', models.CharField(default='', max_length=123, verbose_name='昵称')),
                ('u_check_email', models.IntegerField(default=0, verbose_name='验证邮箱')),
                ('u_link_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
        ),
    ]
