# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=66, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('zhaiyao', models.CharField(max_length=520, verbose_name='文章摘要')),
                ('cover_img', models.ImageField(upload_to='static/articles/cover', verbose_name='文章封面图')),
                ('biaoqian', models.CharField(max_length=256, verbose_name='文章标签')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Article_Count',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('link_article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Article_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='文章类别名称')),
                ('cover', models.ImageField(default='/static/type_cover/default.jpg', upload_to='static/articles/type_cover', verbose_name='文章类配图')),
                ('intro', models.TextField(verbose_name='文章类别描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article_type', verbose_name='父级类型')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article_type', verbose_name='文章分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AddField(
            model_name='article',
            name='user_more_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User_more_info', verbose_name='关联用户更多信息'),
        ),
    ]
