# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_count',
            name='link_article',
        ),
        migrations.AddField(
            model_name='article',
            name='count',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.DeleteModel(
            name='Article_Count',
        ),
    ]
