# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 06:07
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190302_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(),
        ),
    ]
