# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190303_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='zan_num',
            field=models.IntegerField(default=0, verbose_name='点赞量'),
        ),
    ]
