# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_article_zan_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_zan_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link_article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='关联文章')),
                ('link_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
        ),
    ]
