# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-17 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20190312_1534'),
        ('articles', '0005_article_zan_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_pinglun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='评论内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='关联文章')),
                ('pinglun_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article_pinglun', verbose_name='评论自关联父级')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
                ('user_more_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User_more_info', verbose_name='关联用户更多信息')),
            ],
        ),
    ]
