# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_pinglun'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_pinglun',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
