# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_pinglun_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_from',
            field=models.CharField(choices=[('yuanchuang', '原创'), ('zhuanzai', '转载')], default='yuanchuang', max_length=16),
        ),
    ]
