# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-15 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_article_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_zan_log',
            name='link_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='关联文章'),
        ),
    ]
