# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 09:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a_content', models.TextField(verbose_name='回答详情')),
                ('q_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('q_change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('q_link_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
                ('user_more_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User_more_info', verbose_name='关联用户更多信息')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_count',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zan_num', models.IntegerField(default=0, verbose_name='点赞量')),
                ('browse_num', models.IntegerField(default=0, verbose_name='被浏览量')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.Answer', verbose_name='关联回答')),
            ],
        ),
    ]
