# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_answer_answer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='link_question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='关联问题'),
        ),
    ]
