# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20190226_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_count',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='browse_num',
            field=models.IntegerField(default=0, verbose_name='被浏览量'),
        ),
        migrations.DeleteModel(
            name='Question_count',
        ),
    ]
