# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20190303_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_count',
            name='Answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='browse_num',
            field=models.IntegerField(default=0, verbose_name='被浏览量'),
        ),
        migrations.AddField(
            model_name='answer',
            name='zan_num',
            field=models.IntegerField(default=0, verbose_name='点赞量'),
        ),
        migrations.DeleteModel(
            name='Answer_count',
        ),
    ]
